services:
  orbslam3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_VIEWER: 1        # ← dentro do build
    image: orbslam3-custom:latest
    container_name: orbslam3_custom

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,compute,utility

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/datasets:/root/datasets
      - ${HOME}/orbslam3_results:/root/results
      - ${HOME}/orbslam3_custom/scripts:/root/scripts

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    stdin_open: true
    tty: true